//Helper file for the API
//Generated by ChatGPT

import axios from 'axios'

const api = axios.create({
  baseURL: 'http://127.0.0.1:8000', // FastAPI dev server
})

export async function getExampleRows() {
  const res = await api.get('/group_members_example')
  return res.data
}
