"""initial schema - guide assignment models

Revision ID: 7fac8eb8796f
Revises: 
Create Date: 2026-02-24 16:34:02.125485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fac8eb8796f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expertises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expertises_id'), 'expertises', ['id'], unique=False)
    op.create_table('guides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_guides_id'), 'guides', ['id'], unique=False)
    op.create_table('languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_languages_id'), 'languages', ['id'], unique=False)
    op.create_table('sync_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('new_count', sa.Integer(), nullable=True),
    sa.Column('changed_count', sa.Integer(), nullable=True),
    sa.Column('cancelled_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('errors', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_logs_id'), 'sync_logs', ['id'], unique=False)
    op.create_table('availability_patterns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guide_id', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['guide_id'], ['guides.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guide_id')
    )
    op.create_index(op.f('ix_availability_patterns_id'), 'availability_patterns', ['id'], unique=False)
    op.create_table('guide_expertises',
    sa.Column('guide_id', sa.Integer(), nullable=False),
    sa.Column('expertise_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['expertise_id'], ['expertises.id'], ),
    sa.ForeignKeyConstraint(['guide_id'], ['guides.id'], ),
    sa.PrimaryKeyConstraint('guide_id', 'expertise_id')
    )
    op.create_table('guide_languages',
    sa.Column('guide_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['guide_id'], ['guides.id'], ),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.PrimaryKeyConstraint('guide_id', 'language_id')
    )
    op.create_table('tours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clorian_booking_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('required_expertise', sa.String(), nullable=True),
    sa.Column('required_category', sa.String(), nullable=True),
    sa.Column('requested_language_code', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('assigned_guide_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_guide_id'], ['guides.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tours_clorian_booking_id'), 'tours', ['clorian_booking_id'], unique=False)
    op.create_index(op.f('ix_tours_id'), 'tours', ['id'], unique=False)
    op.create_table('availability_exceptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pattern_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['pattern_id'], ['availability_patterns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_availability_exceptions_id'), 'availability_exceptions', ['id'], unique=False)
    op.create_table('availability_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pattern_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['pattern_id'], ['availability_patterns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_availability_slots_id'), 'availability_slots', ['id'], unique=False)
    op.create_table('tour_assignment_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tour_id', sa.Integer(), nullable=False),
    sa.Column('guide_id', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('assigned_by', sa.String(), nullable=True),
    sa.Column('assignment_type', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['guide_id'], ['guides.id'], ),
    sa.ForeignKeyConstraint(['tour_id'], ['tours.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tour_assignment_logs_id'), 'tour_assignment_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tour_assignment_logs_id'), table_name='tour_assignment_logs')
    op.drop_table('tour_assignment_logs')
    op.drop_index(op.f('ix_availability_slots_id'), table_name='availability_slots')
    op.drop_table('availability_slots')
    op.drop_index(op.f('ix_availability_exceptions_id'), table_name='availability_exceptions')
    op.drop_table('availability_exceptions')
    op.drop_index(op.f('ix_tours_id'), table_name='tours')
    op.drop_index(op.f('ix_tours_clorian_booking_id'), table_name='tours')
    op.drop_table('tours')
    op.drop_table('guide_languages')
    op.drop_table('guide_expertises')
    op.drop_index(op.f('ix_availability_patterns_id'), table_name='availability_patterns')
    op.drop_table('availability_patterns')
    op.drop_index(op.f('ix_sync_logs_id'), table_name='sync_logs')
    op.drop_table('sync_logs')
    op.drop_index(op.f('ix_languages_id'), table_name='languages')
    op.drop_table('languages')
    op.drop_index(op.f('ix_guides_id'), table_name='guides')
    op.drop_table('guides')
    op.drop_index(op.f('ix_expertises_id'), table_name='expertises')
    op.drop_table('expertises')
    # ### end Alembic commands ###
