<!-- Example Vue component to display data from the example_table endpoint -->
<!-- Generated by ChatGPT -->
<script setup>
import { ref, onMounted } from "vue";
import { getExampleRows } from "./services/api";

const rows = ref([]);
const loading = ref(true);
const error = ref(null);

onMounted(async () => {
  try {
    rows.value = await getExampleRows();
  } catch (err) {
    error.value = err.message || String(err);
  } finally {
    loading.value = false;
  }
});
</script>

<template>
  <main class="container">
    <h1>Example Table</h1>
    <p>This page shows the contents of a Postgres table via FastAPI.</p>

    <p v-if="loading">Loading...</p>
    <p v-else-if="error" class="error">Error: {{ error }}</p>
    <p v-else-if="!rows.length">No rows found.</p>

    <table v-else class="data-table">
      <thead>
        <tr>
          <!-- Use keys from the first row as column headers -->
          <th v-for="(value, key) in rows[0]" :key="key">
            {{ key }}
          </th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="(row, idx) in rows" :key="idx">
          <td v-for="(value, key) in row" :key="key">
            {{ value }}
          </td>
        </tr>
      </tbody>
    </table>
  </main>
</template>

<style scoped>
.container {
  padding: 2rem;
  font-family: system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
}

.error {
  color: red;
}

.data-table {
  margin-top: 1.5rem;
  border-collapse: collapse;
}

.data-table th,
.data-table td {
  border: 1px solid #ddd;
  padding: 0.5rem 0.75rem;
}
</style>
