#!/usr/bin/env sh

cd frontend && npm run lint:check && npm run test || exit 1

cd ../backend && ./venv/Scripts/python.exe -m ruff check app/ && ./venv/Scripts/python.exe -m ruff format --check app/ && ./venv/Scripts/python.exe -m pytest tests/ --tb=short -q

 
