name: Vercel Frontend Deployment

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"
  workflow_dispatch:

jobs:
  frontend-deploy:
    runs-on: ubuntu-latest

    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.19.0"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build

      - name: Pull Vercel Environment
        run: npx vercel@37.4.1 pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel
        run: npx vercel@37.4.1 deploy --prod --yes --token=${{ secrets.VERCEL_TOKEN }} --debug
